FORMAT: 1A
HOST: https://centralization.morsum.co/api/v1

# Centralization API

## General definition

+ HTTP Verbs GET, POST, PUT, PATCH and DELETE
+ Key <-> Value parameters
+ JSON format
+ Correct usage of HTTP errors like 200, 301, 404, 500, 510…
+ API URIs are user friendly with the structure https://{base_url}/{version}/{scope}/{type}
+ All resource are accessed via HTTPS including referenced images
+ Date and time are represented by Date and DateTime. Both types are formatted according to [ISO 8607](https://www.w3.org/TR/NOTE-datetime). Date is formatted as a complete date - YYYY-MM-DD (e.g. 1997-07-16)- and DateTime as complete date plus hours, minutes and seconds, always with the Z indicator for UTC timezone - YYYY-MM-DDThh:mm:ssZ (e.g. 1997-07-16T19:20:00Z)


## Generic Response format

### Success
HTTP status 2xx

```json
{
    "response": {
      ... // All the responses defined below go here
    }
}
```

For conciseness each operation can specify the response in terms of the response object but, unless specified otherwise, the complete _response_ is structured as above.

Generically for POST, PUT, DELETE and PATCH requests, unless specified otherwise, the response parameter contains the ID of the relevant resource.

```json
{
    "response" : {
        "ID" : Integer // ID of the resource created / updated / deleted
    }
}
```
For POST requests where a new resource is created the success HTTP status is 201. For cases where there is no meaningful content to be returned, as for the logout operation, the success HTTP status is 204 and no content is returned.

### ERROR 4xx or 5xx
HTTP status 4xx for client errors and 5xx for server errors.

```json
{
  "error": {
    "message": String
  }
}
```

### Paging
Requests that return a list of resources can be paged by adding the _page_ and _perPage_ query string parameters. In that case the API will return a subset of the result, with a maximum of _perPage_ items, and a paging object will be added to the response.

```json
{
    "response": ...

    "paging":  {
        "totalPages": Int,
        "perPage": Int,
        "currentPage": Int
        "totalRecords": Int
    }
}
```

<!-- include(Centralization/Groups/Suppliers.apib) -->
<!-- include(Centralization/Groups/Categories.apib) -->
<!-- include(Centralization/Groups/Ingredients.apib) -->
<!-- include(Centralization/Groups/SuppliersProducts.apib) -->
<!-- include(Centralization/Groups/Recipes.apib) -->
<!-- include(Centralization/Groups/RecipesComponents.apib) -->
<!-- include(Centralization/Groups/RecipesIngredientsCategories.apib) -->
<!-- include(Centralization/Groups/RecipesIngredients.apib) -->
<!-- include(Centralization/Groups/RecipesPortionsSizes.apib) -->
<!-- include(Centralization/Groups/RecipesProductionTasksTemplates.apib) -->
<!-- include(Centralization/Groups/Feedbacks.apib) -->
<!-- include(Centralization/Groups/PrepNotes.apib) -->

<!-- include(Centralization/DataStructures.apib) -->