## Error (object)
+ code (string, required)
+ message (string, required)

## QuantityNotAllowed (Error)
+ code: QuantityNotAllowed
+ message: The specified quantity exceeds the number of portions available

## InvalidFulfillmentOptionID (Error)
+ code: InvalidFulfillmentOptionID
+ message: Invalid Fulfillment Option

## InvalidDeliveryTimeID (Error)
+ code: InvalidDeliveryTimeID
+ message:Invalid Delivery Time

## InvalidPaymentMethodID (Error)
+ code: InvalidPaymentMethodID
+ message: Invalid Payment Method ID

## InsufficientBalance (Error)
+ code: InsufficientBalance
+ message: Insufficient balance

## InvalidStoreID (Error)
+ code: InvalidStoreID
+ message: Invalid Store ID

## InvalidCustomizeOptions (Error)
+ code: InvalidCustomizeOptions
+ message: Invalid customize options

## InvalidComboOptions (Error)
+ code: InvalidComboOptions
+ message: Invalid combo options

## InvalidMenuItemID (Error)
+ code: InvalidMenuItemID
+ message: Invalid Menu Item ID

## InvalidPortionID (Error)
+ code: InvalidPortionID
+ message: Invalid Portion ID

## InvalidTransactionID (Error)
+ code: InvalidTransactionID
+ message: Invalid Transaction ID

## InvalidDiscountCode (Error)
+ code: InvalidDiscountCode
+ message: Invalid DiscountCode

