FORMAT: 1A
HOST: https://nutrait.ai/api/v1

# Nutrait API

<!-- include(MobileAPIGeneral.apib) -->

<!-- include(Nutrait/Groups/SSO.apib) -->
<!-- include(Nutrait/Groups/Customers.apib) -->
<!-- include(Nutrait/Groups/Events.apib) -->
<!-- include(Nutrait/Groups/EventTopics.apib) -->
<!-- include(Nutrait/Groups/Recordings.apib) -->
<!-- include(Nutrait/Groups/Highlights.apib) -->
<!-- include(Nutrait/Groups/Recipes.apib) -->
<!-- include(Nutrait/Groups/SectionContents.apib) -->
<!-- include(Nutrait/Groups/ContentReport.apib) -->
<!-- include(Nutrait/Groups/Feedback.apib) -->
<!-- include(Nutrait/Groups/Deeplink.apib) -->
<!-- include(Nutrait/Groups/Communities.apib) -->
<!-- include(Nutrait/Groups/Stores.apib) -->
<!-- include(Nutrait/Groups/PaymentMethods.apib) -->
<!-- include(Nutrait/Groups/Groceries.apib) -->

<!-- include(Nutrait/DataStructures.apib) -->