# Data Structures

## AccessToken (object)
+ token (string, required)
+ expiresIn (string, required)

## UnauthorizedAccessError (Error)
+ code: UnauthorizedAccess
+ message: Unauthorized access or invalid access token

## InvalidSite (Error)
+ code: InvalidSite
+ message: InvalidSite
