# Group Feedback

# Feedback Resource [/feedback]

## Send a customer Feedback [POST]
Send customer feedback
+ Attributes
    + comments: string
    + attachment: Image // Image related to the feedback.
+ Request (application/json)
+ Response 204 (application/json)
